//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadettin_Dursun_Görsel_Programlama_2_Vize
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UcakEntities : DbContext
    {
        public UcakEntities()
            : base("name=UcakEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_BİLET> TBL_BİLET { get; set; }
        public virtual DbSet<TBL_SEFERLER> TBL_SEFERLER { get; set; }
        public virtual DbSet<TBL_UCAK> TBL_UCAK { get; set; }
        public virtual DbSet<TBL_YOLCU> TBL_YOLCU { get; set; }
    }
}
