//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadettin_Dursun_Görsel_Programlama_2_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BİLET
    {
        public int Bilet_Id { get; set; }
        public Nullable<int> Yolcu_Id { get; set; }
        public Nullable<int> Sefer_Id { get; set; }
    
        public virtual TBL_SEFERLER TBL_SEFERLER { get; set; }
        public virtual TBL_YOLCU TBL_YOLCU { get; set; }
    }
}
