//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadettin_Dursun_Görsel_Programlama_2_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_YOLCU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_YOLCU()
        {
            this.TBL_BİLET = new HashSet<TBL_BİLET>();
        }
    
        public int Yolcu_Id { get; set; }
        public string İsim { get; set; }
        public string Yas { get; set; }
        public string Cinsiyet { get; set; }
        public string Yaşlı_Mı { get; set; }
        public string Engelli_Mi { get; set; }
        public string Koltuk_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BİLET> TBL_BİLET { get; set; }
    }
}
