//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadettin_Dursun_Görsel_Programlama_2_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UCAK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_UCAK()
        {
            this.TBL_SEFERLER = new HashSet<TBL_SEFERLER>();
        }
    
        public int Ucak_Id { get; set; }
        public string Ucak_Ad { get; set; }
        public Nullable<int> Koltuk_Sayısı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SEFERLER> TBL_SEFERLER { get; set; }
    }
}
