//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadettin_Dursun_Görsel_Programlama_2_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SEFERLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SEFERLER()
        {
            this.TBL_BİLET = new HashSet<TBL_BİLET>();
        }
    
        public int Sefer_Id { get; set; }
        public string Kalkış_Yer { get; set; }
        public string Varış_Yer { get; set; }
        public Nullable<System.DateTime> Kalkış_Tarih { get; set; }
        public Nullable<System.DateTime> Varış_Tarih { get; set; }
        public Nullable<int> Ucak_Id { get; set; }
        public string Ücret { get; set; }
        public string Sefer_Ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BİLET> TBL_BİLET { get; set; }
        public virtual TBL_UCAK TBL_UCAK { get; set; }
    }
}
